"""empty message

Revision ID: fca043ace058
Revises: 
Create Date: 2025-07-30 17:47:34.051529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca043ace058'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('orders', 'address_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'])
    op.add_column('products', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # op.alter_column('orders', 'address_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # ### end Alembic commands ###
